import type { EligibilityRule } from "@/types";

/**
 * FSA-eligible product keyword rules.
 *
 * Conservative approach: only flag items we're confident are eligible.
 * Users can manually toggle items in the review step.
 *
 * Based on IRS Publication 502 and the CARES Act.
 */
export const ELIGIBILITY_RULES: EligibilityRule[] = [
  {
    category: "otc_medicine",
    label: "OTC Medicine",
    keywords: [
      // Pain relievers
      "ibuprofen",
      "advil",
      "motrin",
      "acetaminophen",
      "tylenol",
      "aspirin",
      "bayer",
      "naproxen",
      "aleve",
      "excedrin",
      // Allergy
      "antihistamine",
      "allergy relief",
      "cetirizine",
      "zyrtec",
      "loratadine",
      "claritin",
      "fexofenadine",
      "allegra",
      "diphenhydramine",
      "benadryl",
      // Cold & flu
      "cold medicine",
      "flu relief",
      "dayquil",
      "nyquil",
      "mucinex",
      "robitussin",
      "sudafed",
      "theraflu",
      "decongestant",
      "cough syrup",
      "dextromethorphan",
      // Digestive
      "antacid",
      "tums",
      "pepto",
      "pepto-bismol",
      "loperamide",
      "imodium",
      "miralax",
      "gas-x",
      "omeprazole",
      "prilosec",
      "ranitidine",
      "famotidine",
      "pepcid",
      "antidiarrheal",
      "laxative",
      // Topical/skin treatments
      "hydrocortisone cream",
      "anti-itch cream",
      "calamine",
      "antifungal cream",
      "clotrimazole",
      "miconazole",
      // Acne (medicated)
      "benzoyl peroxide",
      "salicylic acid acne",
    ],
  },
  {
    category: "first_aid",
    label: "First Aid",
    keywords: [
      "bandage",
      "band-aid",
      "band aid",
      "gauze",
      "bandaging",
      "medical tape",
      "first aid kit",
      "first aid",
      "antiseptic",
      "hydrogen peroxide",
      "isopropyl alcohol",
      "rubbing alcohol",
      "neosporin",
      "bacitracin",
      "antibiotic ointment",
      "wound care",
      "elastic bandage",
      "ace bandage",
      "splint",
      "medical gloves",
      "disposable gloves",
      "sterile",
      "cotton swabs medical",
      "iodine",
      "betadine",
      "saline solution",
      "nasal saline",
      "saline spray",
      "saline rinse",
      "neti pot",
    ],
  },
  {
    category: "medical_equipment",
    label: "Medical Equipment",
    keywords: [
      "blood pressure monitor",
      "blood pressure cuff",
      "sphygmomanometer",
      "thermometer",
      "digital thermometer",
      "infrared thermometer",
      "pulse oximeter",
      "oxygen saturation",
      "nebulizer",
      "cpap",
      "bipap",
      "blood glucose monitor",
      "glucose meter",
      "diabetic",
      "lancet",
      "test strip",
      "insulin",
      "hearing aid",
      "wheelchair",
      "crutches",
      "walker",
      "cane",
      "compression socks",
      "compression stocking",
      "knee brace",
      "ankle brace",
      "back brace",
      "wrist brace",
      "orthopedic",
      "arch support",
      "orthotic",
      "heating pad",
      "ice pack",
      "cold pack",
      "tens unit",
      "pain relief device",
      "massager therapeutic",
    ],
  },
  {
    category: "vision",
    label: "Vision Care",
    keywords: [
      "contact lens",
      "contact lenses",
      "contacts",
      "contact solution",
      "lens solution",
      "contact case",
      "reading glasses",
      "prescription glasses",
      "eyeglasses",
      "sunglasses prescription",
      "eye drops",
      "lubricant eye drops",
      "artificial tears",
      "dry eye",
    ],
  },
  {
    category: "dental",
    label: "Dental Care",
    keywords: [
      "electric toothbrush",
      "oral-b",
      "sonicare",
      "water flosser",
      "waterpik",
      "dental guard",
      "night guard",
      "teeth grinding",
      "bruxism",
      "fluoride treatment",
      "dental floss",
      "orthodontic",
      // Note: regular toothpaste is NOT FSA eligible (cosmetic)
      // Fluoride toothpaste IS eligible if specifically for dental disease prevention
    ],
  },
  {
    category: "feminine_hygiene",
    label: "Feminine Hygiene",
    keywords: [
      // CARES Act (2020) made these FSA eligible
      "tampon",
      "tampons",
      "menstrual pad",
      "period pad",
      "feminine pad",
      "pantyliner",
      "panty liner",
      "menstrual cup",
      "period cup",
      "menstrual disc",
      "period underwear",
      "reusable period",
      "always discreet",
      "light incontinence",
    ],
  },
  {
    category: "baby_health",
    label: "Baby Health",
    keywords: [
      "nasal aspirator",
      "snot sucker",
      "baby thermometer",
      "baby monitor medical",
      "infant nasal",
      // NOT eligible: diapers, formula, baby food, regular baby monitors
    ],
  },
];

/**
 * Navia Benefits expense type dropdown values.
 * Map FSACategory to the Navia form dropdown value.
 * Update based on actual Navia form options during Phase 4.
 */
export const NAVIA_EXPENSE_TYPES: Record<string, string> = {
  otc_medicine: "OTC",
  first_aid: "OTC",
  medical_equipment: "Medical Equipment",
  vision: "Vision",
  dental: "Dental",
  feminine_hygiene: "OTC",
  baby_health: "Medical Equipment",
};
