/**
 * FSA expense list derived from Navia Benefits' official Health Care FSA
 * eligible expenses (PEBB FSA Eligible Expenses 2026).
 *
 * Each entry maps to a Navia expense category and includes Amazon product title
 * keywords that indicate a purchase falls under that category.
 *
 * Coverage statuses:
 *   covered     - Directly eligible
 *   lmn         - Requires a Letter of Medical Necessity
 *   prescription - Requires a valid prescription
 *   not-covered - Explicitly ineligible per Navia
 */

import type { NaviaExpense } from "@/types";

export const NAVIA_EXPENSES: NaviaExpense[] = [
  // ── Eligible (covered) ────────────────────────────────────────────────────

  {
    name: "Allergy & sinus medication",
    status: "covered",
    keywords: [
      "antihistamine",
      "allergy relief",
      "allergy medicine",
      "allergy tablet",
      "allergy capsule",
      "allergy liquid",
      "cetirizine",
      "zyrtec",
      "loratadine",
      "claritin",
      "fexofenadine",
      "allegra",
      "diphenhydramine",
      "benadryl",
      "chlorpheniramine",
      "fluticasone",
      "flonase",
      "nasacort",
      "afrin",
      "xyzal",
      "levocetirizine",
      "sinus relief",
      "sinus congestion",
      "claritin-d",
      "zyrtec-d",
      "allegra-d",
    ],
  },
  {
    name: "Antacids",
    status: "covered",
    keywords: [
      "antacid",
      "tums",
      "rolaids",
      "maalox",
      "mylanta",
      "pepto-bismol",
      "pepto bismol",
      "bismuth subsalicylate",
      "calcium carbonate chewable",
    ],
  },
  {
    name: "Antibiotic ointment",
    status: "covered",
    keywords: [
      "antibiotic ointment",
      "neosporin",
      "bacitracin",
      "triple antibiotic",
      "polysporin",
      "antibiotic cream",
    ],
  },
  {
    name: "Anti-diarrheal",
    status: "covered",
    keywords: [
      "anti-diarrheal",
      "antidiarrheal",
      "loperamide",
      "imodium",
      "diarrhea relief",
    ],
  },
  {
    name: "Antifungal foot cream",
    status: "covered",
    keywords: [
      "antifungal cream",
      "antifungal powder",
      "antifungal spray",
      "antifungal ointment",
      "clotrimazole",
      "miconazole",
      "tinactin",
      "tolnaftate",
      "lotrimin",
      "athlete's foot",
      "athletes foot",
      "terbinafine",
      "lamisil",
      "jock itch",
      "ringworm cream",
    ],
  },
  {
    name: "Anti-gas medication",
    status: "covered",
    keywords: [
      "gas-x",
      "simethicone",
      "gas relief",
      "anti-gas",
      "antigas",
      "beano",
      "phazyme",
      "gas drops",
      "flatulence relief",
    ],
  },
  {
    name: "Anti-itch cream/gel",
    status: "covered",
    keywords: [
      "anti-itch cream",
      "anti-itch gel",
      "anti-itch lotion",
      "hydrocortisone cream",
      "hydrocortisone ointment",
      "calamine",
      "cortizone",
      "itch relief cream",
      "itch relief gel",
      "itch stopping",
    ],
  },
  {
    name: "Antiseptic",
    status: "covered",
    keywords: [
      "antiseptic",
      "hydrogen peroxide",
      "isopropyl alcohol",
      "rubbing alcohol",
      "betadine",
      "povidone-iodine",
      "iodine solution",
      "wound wash",
      "wound cleanser",
    ],
  },
  {
    name: "Asthma treatment",
    status: "covered",
    keywords: [
      "asthma inhaler",
      "peak flow meter",
      "nebulizer",
      "asthma spacer",
      "nebulizer mask",
      "nebulizer tubing",
      "inhaler spacer",
    ],
  },
  {
    name: "Bandages/gauze",
    status: "covered",
    keywords: [
      "bandage",
      "band-aid",
      "band aid",
      "gauze",
      "gauze pad",
      "wound dressing",
      "adhesive bandage",
      "elastic bandage",
      "ace bandage",
      "medical tape",
      "surgical tape",
      "wound closure",
      "butterfly closure",
      "steri-strip",
      "blister bandage",
      "hydrocolloid bandage",
      "tegaderm",
      "sterile pad",
      "non-stick pad",
      "first aid kit",
      "first aid",
    ],
  },
  {
    name: "Blood pressure monitor",
    status: "covered",
    keywords: [
      "blood pressure monitor",
      "blood pressure cuff",
      "sphygmomanometer",
      "bp monitor",
      "wrist blood pressure",
      "upper arm blood pressure",
      "omron blood pressure",
    ],
  },
  {
    name: "Braces (knee, ankle, wrist)",
    status: "covered",
    keywords: [
      "knee brace",
      "ankle brace",
      "wrist brace",
      "back brace",
      "elbow brace",
      "shoulder brace",
      "thumb brace",
      "finger splint",
      "thumb splint",
      "compression sleeve",
      "orthopedic brace",
      "sports brace",
      "hinged brace",
      "mueller brace",
      "ace brace",
    ],
  },
  {
    name: "Breast pump",
    status: "covered",
    keywords: [
      "breast pump",
      "nursing pump",
      "electric breast pump",
      "manual breast pump",
      "milk pump",
      "breast milk pump",
      "spectra pump",
      "medela pump",
    ],
  },
  {
    name: "Burn cream",
    status: "covered",
    keywords: [
      "burn cream",
      "burn gel",
      "burn treatment",
      "burn spray",
      "burn relief gel",
      "first degree burn",
    ],
  },
  {
    name: "Cold/hot pack",
    status: "covered",
    keywords: [
      "ice pack",
      "cold pack",
      "hot pack",
      "heating pad",
      "cold compress",
      "heat pack",
      "reusable ice pack",
      "gel pack",
      "instant cold pack",
      "instant hot pack",
      "electric heating pad",
    ],
  },
  {
    name: "Cold sore treatment",
    status: "covered",
    keywords: [
      "cold sore",
      "abreva",
      "docosanol",
      "cold sore cream",
      "fever blister",
    ],
  },
  {
    name: "Cold/cough medication",
    status: "covered",
    keywords: [
      "cold medicine",
      "cough syrup",
      "dayquil",
      "nyquil",
      "mucinex",
      "robitussin",
      "theraflu",
      "sudafed",
      "dextromethorphan",
      "guaifenesin",
      "cold & flu",
      "cold and flu",
      "nighttime cold",
      "daytime cold",
      "vaporub",
      "vapor rub",
      "vicks",
      "expectorant",
      "cough and cold",
      "chest congestion",
      "nasal decongestant",
    ],
  },
  {
    name: "Contacts & solutions",
    status: "covered",
    keywords: [
      "contact lens",
      "contact lenses",
      "contacts solution",
      "contact solution",
      "lens solution",
      "rewetting drops",
      "acuvue",
      "air optix",
      "biotrue",
      "opti-free",
      "clear care",
      "renu contact",
      "lens case",
      "contact case",
      "lubricant eye drops",
      "artificial tears",
      "dry eye drops",
      "eye drops",
    ],
  },
  {
    name: "Contraceptives",
    status: "covered",
    keywords: [
      "condom",
      "contraceptive",
      "spermicide",
      "diaphragm contraceptive",
      "female condom",
      "plan b",
      "emergency contraceptive",
      "morning after pill",
      "next choice",
    ],
  },
  {
    name: "CPAP machine",
    status: "covered",
    keywords: [
      "cpap",
      "bipap",
      "sleep apnea machine",
      "cpap mask",
      "cpap supplies",
      "cpap hose",
      "cpap filter",
      "cpap tubing",
      "cpap humidifier",
      "cpap headgear",
    ],
  },
  {
    name: "Crutches",
    status: "covered",
    keywords: ["crutches", "crutch", "forearm crutch", "underarm crutch"],
  },
  {
    name: "Diabetic supplies",
    status: "covered",
    keywords: [
      "diabetic",
      "blood glucose monitor",
      "glucose meter",
      "glucometer",
      "lancet",
      "glucose test strip",
      "blood sugar test",
      "continuous glucose",
      "cgm sensor",
      "insulin pump",
      "diabetes supply",
      "ketone strip",
      "diabetic sock",
    ],
  },
  {
    name: "Diaper rash ointment",
    status: "covered",
    keywords: [
      "diaper rash",
      "zinc oxide cream",
      "desitin",
      "balmex",
      "butt cream",
      "butt paste",
      "a+d ointment",
    ],
  },
  {
    name: "Digestive aids",
    status: "covered",
    notes: "Digestive enzymes, lactase, and fiber supplements are covered OTC; probiotics require an LMN.",
    keywords: [
      "digestive enzyme",
      "lactase enzyme",
      "lactaid",
      "lactose intolerance",
      "digestive aid",
      "fiber supplement",
      "benefiber",
      "metamucil",
      "psyllium husk",
      "psyllium fiber",
    ],
  },
  {
    name: "Glucosamine",
    status: "covered",
    notes: "Glucosamine is explicitly FSA eligible without an LMN, unlike most supplements.",
    keywords: ["glucosamine", "glucosamine chondroitin", "glucosamine sulfate"],
  },
  {
    name: "Feminine anti-fungal/anti-itch",
    status: "covered",
    keywords: [
      "feminine antifungal",
      "feminine anti-itch",
      "monistat",
      "vagisil",
      "yeast infection",
      "feminine itch",
      "boric acid suppository",
      "miconazole vaginal",
      "clotrimazole vaginal",
    ],
  },
  {
    name: "Fertility monitor",
    status: "covered",
    keywords: [
      "fertility monitor",
      "ovulation test",
      "ovulation kit",
      "lh test strip",
      "fertility tracker",
      "clearblue fertility",
      "ovulation predictor",
    ],
  },
  {
    name: "Hearing aids & supplies",
    status: "covered",
    keywords: [
      "hearing aid",
      "hearing aids",
      "otc hearing aid",
      "hearing amplifier",
      "hearing loss",
      "behind the ear hearing",
      "hearing aid battery",
      "jabra hearing",
      "lexie hearing",
    ],
  },
  {
    name: "Hemorrhoid medication",
    status: "covered",
    keywords: [
      "hemorrhoid",
      "preparation h",
      "witch hazel pads",
      "anusol",
      "hemorrhoid cream",
      "hemorrhoid ointment",
      "hemorrhoid suppository",
      "rectal itch",
      "tucks pads",
    ],
  },
  {
    name: "Home medical equipment",
    status: "covered",
    keywords: [
      "pulse oximeter",
      "oxygen saturation",
      "oxygen concentrator",
      "nebulizer machine",
      "suction machine",
      "patient lift",
      "hospital bed",
      "transfer belt",
      "gait belt",
    ],
  },
  {
    name: "Insect bite treatment",
    status: "covered",
    keywords: [
      "insect bite",
      "bug bite",
      "after bite",
      "sting relief",
      "bite relief",
      "mosquito bite relief",
      "bee sting relief",
      "itch eraser",
    ],
  },
  {
    name: "Laxative",
    status: "covered",
    keywords: [
      "laxative",
      "miralax",
      "polyethylene glycol",
      "dulcolax",
      "bisacodyl",
      "senna laxative",
      "senokot",
      "ex-lax",
      "gentle laxative",
      "stimulant laxative",
    ],
  },
  {
    name: "Lice treatment products",
    status: "covered",
    keywords: [
      "lice treatment",
      "lice shampoo",
      "nix lice",
      "rid lice",
      "lice comb",
      "head lice",
      "lice killer",
      "liceguard",
      "lice spray",
      "nit comb",
    ],
  },
  {
    name: "Menstrual care products",
    status: "covered",
    keywords: [
      "tampon",
      "tampons",
      "menstrual pad",
      "period pad",
      "feminine pad",
      "menstrual cup",
      "period cup",
      "menstrual disc",
      "period underwear",
      "panty liner",
      "pantyliner",
      "reusable pad",
      "period protection",
      "always ultra thin",
      "kotex",
    ],
  },
  {
    name: "Motion sickness relief",
    status: "covered",
    keywords: [
      "motion sickness",
      "dramamine",
      "dimenhydrinate",
      "bonine",
      "meclizine",
      "sea band",
      "travel sickness",
      "car sickness",
    ],
  },
  {
    name: "Pain relievers",
    status: "covered",
    keywords: [
      "ibuprofen",
      "advil",
      "motrin",
      "acetaminophen",
      "tylenol",
      "aspirin",
      "naproxen",
      "aleve",
      "excedrin",
      "pain reliever",
      "pain relief tablet",
      "pain relief caplet",
      "bayer aspirin",
      "headache relief",
    ],
  },
  {
    name: "Parasitic treatment",
    status: "covered",
    keywords: [
      "pinworm",
      "reese's pinworm",
      "anti-parasitic",
      "pyrantel",
      "worm treatment",
    ],
  },
  {
    name: "Pregnancy test",
    status: "covered",
    keywords: [
      "pregnancy test",
      "home pregnancy test",
      "hpt",
      "clearblue pregnancy",
      "first response pregnancy",
    ],
  },
  {
    name: "Prenatal vitamins",
    status: "covered",
    keywords: [
      "prenatal vitamin",
      "prenatal multivitamin",
      "prenatal",
      "postnatal vitamin",
      "folic acid prenatal",
    ],
  },
  {
    name: "Reading glasses",
    status: "covered",
    keywords: ["reading glasses", "readers glasses", "magnifying glasses reading"],
  },
  {
    name: "Saline nasal spray",
    status: "covered",
    keywords: [
      "saline nasal spray",
      "nasal saline",
      "nasal rinse",
      "sinus rinse",
      "neti pot",
      "simply saline",
      "ocean spray nasal",
      "nasal wash",
      "saline spray",
    ],
  },
  {
    name: "Sleep aids & sedatives",
    status: "covered",
    keywords: [
      "sleep aid",
      "melatonin",
      "zzzquil",
      "unisom",
      "diphenhydramine sleep",
      "doxylamine",
      "nighttime sleep",
      "sleep supplement",
      "sleep gummy",
      "sleep tablet",
      "somtabs",
    ],
  },
  {
    name: "Smoking cessation programs & products",
    status: "covered",
    keywords: [
      "nicotine patch",
      "nicorette",
      "nicotine gum",
      "smoking cessation",
      "nicotine lozenge",
      "nicotine inhaler",
      "quit smoking",
      "stop smoking",
      "nicoderm",
    ],
  },
  {
    name: "Stool softener",
    status: "covered",
    keywords: [
      "stool softener",
      "colace",
      "docusate sodium",
      "docusate calcium",
      "peri-colace",
    ],
  },
  {
    name: "Sunscreen SPF 15 or more",
    status: "covered",
    keywords: [
      "sunscreen",
      "sunblock",
      "sun protection",
      "mineral sunscreen",
      "spf 15",
      "spf 30",
      "spf 50",
      "broad spectrum spf",
      "uv protection",
    ],
  },
  {
    name: "Thermometer",
    status: "covered",
    keywords: [
      "thermometer",
      "digital thermometer",
      "infrared thermometer",
      "ear thermometer",
      "forehead thermometer",
      "temporal thermometer",
      "rectal thermometer",
      "oral thermometer",
    ],
  },
  {
    name: "Throat lozenges",
    status: "covered",
    keywords: [
      "throat lozenge",
      "cough drop",
      "halls cough",
      "ricola",
      "chloraseptic",
      "sucrets",
      "throat relief",
      "sore throat lozenge",
      "throat soothing",
    ],
  },
  {
    name: "Walker",
    status: "covered",
    keywords: ["walker", "rollator", "rolling walker", "folding walker"],
  },
  {
    name: "Wart treatment",
    status: "covered",
    keywords: [
      "wart remover",
      "wart treatment",
      "compound w",
      "freeze wart",
      "wart off",
      "salicylic acid wart",
    ],
  },
  {
    name: "Wheelchair & repair",
    status: "covered",
    keywords: [
      "wheelchair",
      "power wheelchair",
      "manual wheelchair",
      "transport wheelchair",
      "wheelchair cushion",
    ],
  },
  {
    name: "Compression socks/stockings",
    status: "lmn",
    notes:
      "Require an LMN to establish medical necessity; only the excess cost over regular socks is reimbursable.",
    keywords: [
      "compression socks",
      "compression stocking",
      "compression hosiery",
      "graduated compression",
      "medical compression",
    ],
  },
  {
    name: "Orthodontia",
    status: "covered",
    keywords: [
      "dental night guard",
      "night guard",
      "dental guard",
      "teeth grinding guard",
      "bruxism guard",
      "orthodontic wax",
      "retainer case",
    ],
  },

  {
    name: "Arnica gel",
    status: "covered",
    keywords: ["arnica gel", "arnica cream", "arnica ointment", "arnica montana"],
  },
  {
    name: "TENS unit",
    status: "covered",
    notes: "Transcutaneous Electrical Nerve Stimulation devices are qualified medical devices.",
    keywords: [
      "tens unit",
      "tens machine",
      "tens device",
      "transcutaneous electrical",
      "electrotherapy",
      "ems unit",
      "muscle stimulator",
      "nerve stimulator",
      "ireliev tens",
      "compex tens",
    ],
  },
  {
    name: "Topical analgesic (muscle/arthritis)",
    status: "covered",
    keywords: [
      "biofreeze",
      "icy hot",
      "icyhot",
      "bengay",
      "ben gay",
      "salonpas",
      "tiger balm",
      "topical pain relief",
      "muscle rub",
      "arthritis cream",
      "menthol pain relief",
      "camphor pain relief",
      "diclofenac topical",
      "voltaren gel",
    ],
  },
  {
    name: "Oral rehydration / electrolytes",
    status: "covered",
    notes: "Oral rehydration salts and electrolyte solutions for medical rehydration are FSA eligible.",
    keywords: [
      "oral rehydration",
      "rehydration solution",
      "pedialyte",
      "liquid iv",
      "drip drop",
      "nuun electrolyte",
      "electrolit",
      "electrolyte solution",
    ],
  },
  {
    name: "Ear drops / ear wax removal",
    status: "covered",
    keywords: [
      "ear drops",
      "ear wax removal",
      "earwax removal",
      "debrox",
      "ear irrigation",
      "ear cleaning kit",
      "ear cleaning drops",
    ],
  },
  {
    name: "Medical alert bracelet",
    status: "covered",
    keywords: [
      "medical alert bracelet",
      "medical id bracelet",
      "medical alert necklace",
      "medical id tag",
    ],
  },
  {
    name: "Sitz bath",
    status: "covered",
    notes: "Sitz baths are FSA eligible medical treatment devices (e.g., for hemorrhoid or postpartum care).",
    keywords: ["sitz bath", "sitz tub", "perineal soak"],
  },
  {
    name: "Vaporizer / steam inhaler",
    status: "covered",
    keywords: [
      "vaporizer",
      "steam inhaler",
      "personal steamer",
      "facial steamer",
      "steam vaporizer",
    ],
  },
  {
    name: "Therapy eye mask",
    status: "covered",
    notes: "Heated or cold therapy eye masks for dry eye or medical eye conditions are FSA eligible.",
    keywords: [
      "therapy eye mask",
      "heated eye mask",
      "warm compress eye",
      "eye therapy mask",
      "mgd eye mask",
      "bruder eye mask",
    ],
  },
  {
    name: "Face mask (COVID-19 prevention)",
    status: "covered",
    notes: "Face masks to prevent COVID-19 are FSA eligible.",
    keywords: ["n95 mask", "kn95 mask", "covid mask", "face mask covid"],
  },
  {
    name: "Wound seal / hemostatic",
    status: "covered",
    keywords: [
      "wound seal",
      "wound powder",
      "hemostatic",
      "quikclot",
      "celox",
      "bloodstop",
      "wound clotting",
    ],
  },
  {
    name: "Anti-snore guard",
    status: "covered",
    keywords: [
      "anti-snore",
      "anti snore guard",
      "snore guard",
      "snoring mouthpiece",
      "snore mouthpiece",
      "snore stopper",
      "mandibular advancement",
      "sleep snore",
    ],
  },
  {
    name: "Arch support/insoles",
    status: "covered",
    keywords: [
      "arch support",
      "orthotic insole",
      "orthotic insert",
      "shoe insert",
      "heel insert",
      "plantar fasciitis insole",
      "foot insole",
      "dr scholl",
      "dr. scholl",
      "superfeet",
      "powerstep insole",
    ],
  },
  {
    name: "Arm sling",
    status: "covered",
    keywords: ["arm sling", "shoulder sling", "wrist sling"],
  },
  {
    name: "Arthritis glove",
    status: "covered",
    keywords: [
      "arthritis glove",
      "compression glove",
      "rheumatoid glove",
      "joint glove",
    ],
  },
  {
    name: "At-home COVID-19 test",
    status: "covered",
    notes: "Eligible when not already covered by a health plan.",
    keywords: [
      "covid test",
      "covid-19 test",
      "coronavirus test",
      "antigen test kit",
      "binaxnow",
      "flowflex covid",
      "ihealth covid",
      "quickvue covid",
    ],
  },
  {
    name: "At-home drug test",
    status: "covered",
    keywords: ["drug test kit", "home drug test", "urine drug test"],
  },
  {
    name: "Athletic mouth guard",
    status: "covered",
    keywords: [
      "mouth guard",
      "mouthguard",
      "sports mouth guard",
      "athletic mouth guard",
    ],
  },
  {
    name: "Athletic tape / kinesiology tape",
    status: "covered",
    keywords: [
      "athletic tape",
      "kinesiology tape",
      "kt tape",
      "sports tape",
      "rock tape",
      "rocktape",
      "pre-wrap tape",
    ],
  },
  {
    name: "Acupressure mat",
    status: "covered",
    keywords: ["acupressure mat", "acupressure wrist", "acupressure pad"],
  },
  {
    name: "Baby breathing monitor",
    status: "covered",
    keywords: [
      "baby breathing monitor",
      "infant breathing monitor",
      "baby monitor oxygen",
      "owlet",
      "snuza",
    ],
  },
  {
    name: "Bed wetting / incontinence aids",
    status: "covered",
    notes:
      "Eligible for incontinence treatment in older adults/children; infant diapers are not eligible.",
    keywords: [
      "bed wetting",
      "bedwetting alarm",
      "incontinence pad",
      "incontinence underwear",
      "adult diaper",
      "depends underwear",
      "always discreet",
      "poise pad",
      "incontinence brief",
    ],
  },
  {
    name: "AED (defibrillator)",
    status: "covered",
    keywords: [
      "aed",
      "automated external defibrillator",
      "defibrillator",
      "cardiac monitor",
    ],
  },
  {
    name: "Antipyretics / fever reducers",
    status: "covered",
    keywords: [
      "fever reducer",
      "fever relief",
      "children's tylenol",
      "children's advil",
      "children's ibuprofen",
      "infants' tylenol",
      "antipyretic",
    ],
  },
  {
    name: "Hand sanitizer (60%+ alcohol)",
    status: "covered",
    notes: "Must contain at least 60% alcohol.",
    keywords: [
      "hand sanitizer",
      "hand sanitiser",
      "antibacterial hand sanitizer",
      "purell",
      "germ-x",
    ],
  },

  // ── Eligible with Letter of Medical Necessity (LMN) ──────────────────────

  {
    name: "Water flosser",
    status: "lmn",
    notes:
      "Eligible with an LMN from a dentist or doctor documenting a specific oral health condition (e.g., gum disease).",
    keywords: [
      "water flosser",
      "waterpik",
      "oral irrigator",
      "dental irrigator",
    ],
  },
  {
    name: "Acne treatment",
    status: "covered",
    notes: "OTC acne treatments are FSA eligible without additional documentation.",
    keywords: [
      "acne treatment",
      "benzoyl peroxide",
      "salicylic acid acne",
      "adapalene",
      "differin",
      "acne cream",
      "acne gel",
      "acne wash",
    ],
  },
  {
    name: "Vitamins/supplements",
    status: "lmn",
    notes:
      "Generally not eligible; reimbursable only with an LMN documenting a medical necessity (e.g., diagnosed deficiency).",
    keywords: [
      "multivitamin",
      "vitamin d supplement",
      "vitamin c supplement",
      "fish oil",
      "omega 3",
      "zinc supplement",
      "iron supplement",
      "magnesium supplement",
      "vitamin b12",
      "calcium supplement",
      "vitamin supplement",
      "dietary supplement",
    ],
  },
  {
    name: "Air filter / air purifier",
    status: "lmn",
    notes:
      "Eligible with an LMN from a doctor documenting a medical condition (e.g., asthma, severe allergies) that requires cleaner air.",
    keywords: [
      "air purifier",
      "hepa filter",
      "air filter",
      "hepa air",
      "air cleaner",
      "winix air",
      "levoit air",
      "blueair purifier",
    ],
  },
  {
    name: "Aloe vera",
    status: "lmn",
    notes:
      "Aloe vera creams/ointments are eligible with an LMN; not eligible as a general moisturizer.",
    keywords: ["aloe vera gel", "aloe vera cream", "aloe vera ointment"],
  },
  {
    name: "Alopecia treatment",
    status: "lmn",
    notes:
      "Eligible with an LMN for medically-diagnosed alopecia; normal male-pattern baldness treatment is ineligible as cosmetic.",
    keywords: [
      "alopecia treatment",
      "hair loss treatment medical",
      "minoxidil prescription",
    ],
  },
  {
    name: "Anti-embolism socks/stockings",
    status: "lmn",
    notes:
      "May require an LMN; only the excess cost over regular socks is reimbursable.",
    keywords: [
      "anti-embolism stocking",
      "ted hose",
      "compression stocking medical",
      "dvt stocking",
    ],
  },
  {
    name: "Humidifier",
    status: "lmn",
    notes:
      "Eligible with an LMN when purchased primarily to treat a medical condition (e.g., asthma, chronic sinusitis).",
    keywords: [
      "humidifier",
      "cool mist humidifier",
      "warm mist humidifier",
      "ultrasonic humidifier",
      "evaporative humidifier",
      "vicks humidifier",
      "levoit humidifier",
    ],
  },
  {
    name: "LED light therapy",
    status: "lmn",
    notes:
      "Eligible with an LMN establishing medical necessity for FSA reimbursement.",
    keywords: [
      "led light therapy",
      "red light therapy",
      "infrared therapy device",
      "phototherapy device",
      "led therapy mask",
      "blue light acne device",
    ],
  },
  {
    name: "Ergonomic chair",
    status: "lmn",
    notes:
      "Eligible with an LMN establishing a specific medical condition (e.g., back injury, chronic pain) requiring ergonomic support.",
    keywords: [
      "ergonomic chair",
      "ergonomic office chair",
      "lumbar support chair",
      "orthopedic chair",
    ],
  },
  {
    name: "Probiotics",
    status: "lmn",
    notes:
      "Probiotics require an LMN from a medical professional to be FSA eligible.",
    keywords: [
      "probiotic supplement",
      "probiotic capsule",
      "culturelle",
      "align probiotic",
      "renew life probiotic",
      "garden of life probiotic",
      "florastor",
    ],
  },
  {
    name: "Scar treatment",
    status: "lmn",
    notes: "Scar treatment products require an LMN to establish medical necessity.",
    keywords: [
      "scar treatment",
      "scar gel",
      "scar cream",
      "scar silicone sheet",
      "mederma",
      "silicone scar",
    ],
  },
  {
    name: "Wig (medical hair loss)",
    status: "lmn",
    notes:
      "Wigs are FSA eligible with an LMN when hair loss is due to disease or medical treatment (e.g., chemotherapy).",
    keywords: ["medical wig", "chemo wig", "cranial prosthesis"],
  },
  {
    name: "Massage therapy device",
    status: "lmn",
    notes:
      "Massage therapy requires an LMN establishing treatment of a specific medical condition.",
    keywords: [
      "massage gun",
      "percussive massager",
      "theragun",
      "hypervolt",
      "massage chair",
      "shiatsu massager",
      "back massager",
    ],
  },
];

/**
 * Items that are explicitly NOT eligible per Navia's FSA expense list.
 * Used for reference/documentation — these do not appear in NAVIA_EXPENSES
 * because they should never generate an eligibility match.
 *
 * Notably: electric toothbrushes, teeth whitening, gym memberships, hygiene
 * products, and activity trackers are ineligible. Water flossers (Waterpik)
 * require an LMN and are tracked separately above.
 */
export const NOT_COVERED_EXAMPLES = [
  "Electric toothbrush/picks",
  "Teeth whitening",
  "Gym membership",
  "Fitness programs (general)",
  "Activity tracker",
  "Hygiene products",
  "Toiletries",
  "Toothbrush",
  "Toothpaste",
  "Airborne",
  "Hair growth products (cosmetic/male pattern baldness)",
  "Aromatherapy",
  "Baby formula (standard)",
  "Anti-aging face creams (cosmetic)",
  "Laser hair removal",
  "Cosmetic surgery",
  "Electrolysis (cosmetic hair removal)",
  "Legal fees",
  "Medical marijuana",
  "Diet food",
] as const;
